# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoCalc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demoCalc

 
  target 'demoCalcTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demoCalc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demoCalc-tvOS

  target 'demoCalc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
